# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: FEATURE RELEASE BUILD WITH MAVEN

on:
  workflow_dispatch:
  push:
    branchs:
      - 'release*'
      - 'master'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Build with Maven
        run: mvn -B package --file pom.xml


      - name: deploy file to server
        uses: wlixcc/SFTP-Deploy-Action@master
        with:
          username: '${{ secrets.CI_USER }}'
          server: '${{ secrets.SERVER_IP }}'
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          local_path: './target/*.tar.gz'
          remote_path: '/opt/build/'

      - name: auto upgrade server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.CI_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: /opt/build/upgrade.sh


